//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_GJS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class M_PAGE
    {
        [Display(Name = "Trang")]
        public long PAGE_COTRACT_CD { get; set; }
       
        [DataType(DataType.Text)]
        [Display(Name = "Tiêu đề ")]
        public string PAGE_COTRACT_TITLE { get; set; }
        
        [DataType(DataType.Text)]
        [Display(Name = "Nội dung")]
        public string PAGE_COTRACT_CONTENT { get; set; }
        [DataType(DataType.Text)]
        [Display(Name = "Danh mục trang")]
        public Nullable<long> CATEGORY_PAGE_CD { get; set; }
        public Nullable<long> STATUS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    
        public virtual O_CATEGORY_PAGE O_CATEGORY_PAGE { get; set; }
    }
}
