//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_GJS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class O_CATEGORY_PRODUCT
    {
        public O_CATEGORY_PRODUCT()
        {
            this.O_CATEGORY_PRODUCT_DETAIL = new HashSet<O_CATEGORY_PRODUCT_DETAIL>();
            this.O_PRODUCT = new HashSet<O_PRODUCT>();
        }

        [Display(Name = "Danh mục sản phẩm")]
        public long CATEGORY_PRODUCT_CD { get; set; }
        [DataType(DataType.Text)]
        [Display(Name = "Mã danh mục sản phẩm")]
        public string CATEGORY_PRODUCT_CODE { get; set; }
        [DataType(DataType.Text)]
        [Display(Name = "Tên danh mục sản phẩm")]
        public string CATEGORY_PRODUCT_NAME { get; set; }
        [DataType(DataType.Text)]
        [Display(Name = "Thẻ alt")]
        public string TAG_ALT { get; set; }
        public Nullable<long> STATUS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    
        public virtual ICollection<O_CATEGORY_PRODUCT_DETAIL> O_CATEGORY_PRODUCT_DETAIL { get; set; }
        public virtual ICollection<O_PRODUCT> O_PRODUCT { get; set; }
    }
}
