//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_GJS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class O_CATEGORY_PRODUCT_DETAIL
    {
        public O_CATEGORY_PRODUCT_DETAIL()
        {
            this.O_PRODUCT = new HashSet<O_PRODUCT>();
        }
        [Display(Name = "Chi tiết danh mục sản phẩm")]
        public long CATEGORY_PRODUCT_DETAIL_CD { get; set; }
        [Display(Name = "Danh mục sản phẩm")]
        public Nullable<long> CATEGORY_PRODUCT_CD { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin !!!")]
        [DataType(DataType.Text)]
        [Display(Name = "Mã ctdm sản phẩm")]
        public string CATEGORY_PRODUCT_DETAIL_CODE { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin !!!")]
        [DataType(DataType.Text)]
        [Display(Name = "Tên ctdm sản phẩm")]
        public string CATEGORY_PRODUCT_DETAIL_NAME { get; set; }
        [DataType(DataType.Text)]
        [Display(Name = "Thẻ alt")]
        public string TAG_ALT { get; set; }
        public Nullable<long> STATUS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    
        public virtual O_CATEGORY_PRODUCT O_CATEGORY_PRODUCT { get; set; }
        public virtual ICollection<O_PRODUCT> O_PRODUCT { get; set; }
    }
}
