//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_GJS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class O_CITIES
    {
        public O_CITIES()
        {
            this.O_BRANCH = new HashSet<O_BRANCH>();
            this.D_CITIES_DETAIL = new HashSet<D_CITIES_DETAIL>();
        }
        [Display(Name = "Khu vực")]
        public long CITIES_CD { get; set; }
        [DataType(DataType.Text)]
        [Display(Name = "Mã khu vực")]
        
        public string CITIES_CODE { get; set; }
    
        [DataType(DataType.Text)]
        [Display(Name = "Tên khu vực")]
        public string CITIES_NAME { get; set; }

        public Nullable<long> STATUS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    
        public virtual ICollection<O_BRANCH> O_BRANCH { get; set; }
        public virtual ICollection<D_CITIES_DETAIL> D_CITIES_DETAIL { get; set; }
    }
}
