//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_GJS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class O_HOME_GROUP_PHOTO
    {
        public long HOME_GROUP_PHOTO_CD { get; set; }
        [Display(Name = "Hình ảnh 1")]
        public string PHOTO_URL_1 { get; set; }
        [Display(Name = "Hình ảnh 2")]
        public string PHOTO_URL_2 { get; set; }
        [Display(Name = "Hình ảnh 3")]
        public string PHOTO_URL_3 { get; set; }
        [Display(Name = "Hình ảnh 4")]
        public string PHOTO_URL_4 { get; set; }
        [Display(Name = "Hình ảnh 5")]
        public string PHOTO_URL_5 { get; set; }
        [Display(Name = "Hình ảnh 6")]
        public string PHOTO_URL_6 { get; set; }
        public Nullable<long> STATUS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    }
}
