//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_GJS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class O_HOME_INTRODUCTION
    {
        public long O_HOME_INTRODUCTION_CD { get; set; }
        [Display(Name = "Nội dụng")]
        public string O_HOME_INTRODUCTION_CONTENT { get; set; }
         [Display(Name = "Tên người gửi")]
        public string O_HOME_INTRODUCTION_AUTHOR { get; set; }
        [Display(Name = "Hình ảnh")]
        public string O_HOME_INTRODUCTION_PHOTO { get; set; }
        public Nullable<long> STATUS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    }
}
