//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_GJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_HOME_SERVICE_DETAIL
    {
        public long HOME_SERVICE_DETAIL_CD { get; set; }
        public string HOME_SERVICE_DETAIL_PHOTO { get; set; }
        public string HOME_SERVICE_DETAIL_DESCRIPTION { get; set; }
        public string HOME_SERVICE_DETAIL_ACTION { get; set; }
        public string HOME_SERVICE_DETAIL_TITLE { get; set; }
        public Nullable<long> STATUS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    }
}
