//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_GJS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class O_NEWS
    {
        public O_NEWS()
        {
            this.O_NEWS_HIGHLIGHTS = new HashSet<O_NEWS_HIGHLIGHTS>();
            this.O_NEWS_NEW = new HashSet<O_NEWS_NEW>();
        }
        [Display(Name = "Tin tức")]
        public long NEWS_CD { get; set; }
     
        [DataType(DataType.Text)]
        [Display(Name = "Tiêu đề")]
        public string NEWS_TITLE { get; set; }
        
        [DataType(DataType.Text)]
        [Display(Name = "Mô tả ngắn gọn")]
        public string NEW_DESCRIPTIONS { get; set; }
    
        [DataType(DataType.Text)]
        [Display(Name = "Nội dụng")]
        public string NEWS_CONTENT { get; set; }
   
        [DataType(DataType.Text)]
        [Display(Name = "Hình ảnh")]
        public string IMAGE_NEWS { get; set; }
        [Display(Name = "Loại tin tức")]
        public Nullable<long> CATEGORY_NEWS_CD { get; set; }
        [DataType(DataType.Text)]
        [Display(Name = "Nguồn tin")]
        public string SOURCE_COPY { get; set; }
        [DataType(DataType.Text)]
        [Display(Name = "Thẻ alt")]
        public string TAG_ALT { get; set; }
        public Nullable<long> EMPLOYEE_CD { get; set; }
        public Nullable<long> STATUS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        [Display(Name = "Ngày tạo")]
        [DisplayFormat(DataFormatString="{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    
        public virtual M_EMPLOYEE M_EMPLOYEE { get; set; }
        public virtual O_CATEGORY_NEWS O_CATEGORY_NEWS { get; set; }
        public virtual ICollection<O_NEWS_HIGHLIGHTS> O_NEWS_HIGHLIGHTS { get; set; }
        public virtual ICollection<O_NEWS_NEW> O_NEWS_NEW { get; set; }
        public virtual ICollection<O_NEWS_HOME> O_NEWS_HOME { get; set; }
    }
}
