//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_GJS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class O_SEO
    {
        public long CD { get; set; }
        [DataType(DataType.Text)]
        [Display(Name = "Icon hình")]
        public string HREF_ICON { get; set; }
        [DataType(DataType.Text)]
        [Display(Name = "Thẻ title")]
        public string TITILE { get; set; }
        [DataType(DataType.Text)]
        [Display(Name = "Thẻ meta description")]
        public string META_DES { get; set; }
        [DataType(DataType.Text)]
        [Display(Name = "Thẻ meta keywords")]
        public string META_KEYWORDS { get; set; }
        [DataType(DataType.Text)]
        [Display(Name = "Thẻ meta robots")]
        public string META_ROBOTS { get; set; }
        [DataType(DataType.Text)]
        [Display(Name = "Thẻ meta revisit")]
        public string META_REVISIT { get; set; }
        public Nullable<long> STATUS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    }
}
