//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_GJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_PST
    {
        public S_PST()
        {
            this.O_USER_PST = new HashSet<O_USER_PST>();
        }
    
        public long PST_CD { get; set; }
        public string PST_CODE { get; set; }
        public string PST_NAME { get; set; }
        public Nullable<long> STATUS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    
        public virtual ICollection<O_USER_PST> O_USER_PST { get; set; }
    }
}
