//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_GJS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class S_USER
    {
        public S_USER()
        {
            this.O_USER_CUSTOMER = new HashSet<O_USER_CUSTOMER>();
            this.O_USER_EMPLOYEE = new HashSet<O_USER_EMPLOYEE>();
            this.O_USER_PST = new HashSet<O_USER_PST>();
        }

       
        public long USER_CD { get; set; }
       
        [Required(ErrorMessage = "Vui lòng nhập thông tin !!!")]
        [DataType(DataType.Text)]
        [Display(Name = "Tên đăng nhập")]
        public string USER_NAME { get; set; }
        [DataType(DataType.Password)]
        [Display(Name = "Mật khẩu")]
        public string USER_PASS { get; set; }
        [Display(Name = "Quyền")]
        public Nullable<long> STATUS { get; set; }
        
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    
        public virtual ICollection<O_USER_CUSTOMER> O_USER_CUSTOMER { get; set; }
        public virtual ICollection<O_USER_EMPLOYEE> O_USER_EMPLOYEE { get; set; }
        public virtual ICollection<O_USER_PST> O_USER_PST { get; set; }
    }
}
